# Axmos Technologies 
# Axmos Back End Example is an Open Source Project
# This file is just an example and is distributed without any warranty
# Made with love
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {SERVICE_NAME}
  labels:
    cloud.googleapis.com/location: {REGION}
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        autoscaling.knative.dev/maxScale: '100'
        run.googleapis.com/startup-cpu-boost: 'true'  
    spec:
      containerConcurrency: 80
      containers:
        - image: {REGION}-docker.pkg.dev/{CICD_PROJECT_ID}/{ARTIFACT_REPOSITORY}/{SERVICE_NAME}:{VERSION}
          ports:
            - containerPort: 8080
          env:
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: DB_PASS
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: DB_USER
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: DB_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: DB_NAME
            - name: AUTH_PLATFORM_KEY
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: AUTH_PLATFORM_KEY
            - name: AUTH_PLATFORM_DOMAIN
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: AUTH_PLATFORM_DOMAIN
            - name: DATASET
              value: {CICD_PROJECT_ID}
            - name: DIFYAI_API_KEY
              value: {DIFYAI_API_KEY}
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
